name: CD - Deploy to Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy to Dev Workspace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install databricks-cli

      - name: Deploy notebooks to /dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
        run: |
          databricks workspace import_dir Notebooks /live --overwrite

