name: CI - Check Notebooks

on:
  push:
    branches: [main, feature/*]

jobs:
  check-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Notebook Files Exist
        run: |
          if [ -d "Notebooks" ]; then
            echo "Notebook folder exists"
          else
            echo "Notebook folder is missing"
            exit 1
          fi
